### ISSUE TITLE
[PE-D][Tester C] findT not able to select multiple matching tasks

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-F11-4/tp#215]
As you can see the keywords used here to select the description are "Finish" and "guide" which should match with two tasks. However, the tasks are not being found properly according to these keywords.
![Screenshot 2022-10-28 at 4.54.44 PM.png](https://raw.githubusercontent.com/nareus/ped/main/files/8780903a-9c99-4923-a18c-1d80322789a3.png)

![Screenshot 2022-10-28 at 4.55.05 PM.png](https://raw.githubusercontent.com/nareus/ped/main/files/41925e2e-576b-47d5-81a1-e9812243a581.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: nareus/ped#6

**Comment by junwei-tan** [comment]
duplicate
