### ISSUE TITLE
[PE-D][Tester A] [Suggestion] Have a section for archived tasks

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-F11-4/tp#219]
Create another tab which shows a list of archived tasks, saving users the hassle of needing to input the command to access them.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: Francis-Tan/ped#4

**Comment by ryanguai** [comment]
No more UI changes in v1.4

**Comment by junwei-tan** [comment]
ui changes, cannot change in 1.4
