### ISSUE TITLE
Replace placeholder information on AboutUs with personal information

### ISSUE THREAD

**Issue by ryanguai** [AY2223S1-CS2103T-F11-4/tp#42]
John Doe - Ryan
Jane Doe - Felicia
Johnny Doe - Jun Wei
Jean Doe - Nicole
James Doe - Alvin

**Comment by alvintfl** [comment]
Merged Ryan's info.

**Comment by alvintfl** [comment]
Merged Felicia's info.

**Comment by alvintfl** [comment]
Merged JunWei's info.
